server:
  port: 3344

spring:
   application:
      name: microservicecloud-config
   cloud: # 在 github 上创建仓库
      config:
        server:
          git:
            uri: https://github.com/tsubasatei/microservicecloud-config.git  # GitHub上面的仓库名

